### ISSUE TITLE
key.rsa?

### ISSUE THREAD

**Issue by mroutis** [cirocosta/mylinux#10]
I was lurking reddit, somehow ended reading your dotfiles, is it safe to have a private key on GitHub?

https://github.com/cirocosta/mylinux/blob/master/aws/keys/key.rsa#L1

**Comment by cirocosta** [comment]
Hey @mroutis ,


I'd say that you're totally right - **it's not safe** 👍 thx for pointing out!

Given that the whole point of this is to serve as a disposable environment for some quick testing, maybe it's more interesting to generate they key whenever I bootstrap it (there's https://www.terraform.io/docs/providers/tls/r/private_key.html).

Another option is to keep it in 1password and then make clear in the readme that the user should provide its own key (useful for those running long-running instances).

wdyt?

thx!

**Comment by mroutis** [comment]
Sounds good, @cirocosta, whatever works for you, man.
There's also `git-crypt` https://github.com/AGWA/git-crypt I've been using it for a couple of months and it has been a bless to work with :+1:
